default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeoute: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password:
  database: words_production
  username: words
  password: <%= ENV['WORDS_DATABASE_PASSWORD'] %>
